name: Auto deploy dbt models in data_warehouse folder
run-name: Auto deploy dbt models for ${{ github.actor }} 🚀
on:
  push:
    paths:
      - 'data_warehouse/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    - name: dbt-action
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt run --target engdev -m logins"
      env:
        DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
