name: Auto deploy dbt models in data_warehouse folder
run-name: Auto deploy dbt models for ${{ github.actor }} 🚀
on:
  push:
    paths:
      - 'data_warehouse/**'
      - '**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: ls
      - run: env 
