name: GitHub Actions Demo
run-name: Running dbt update for ${{ github.actor }} 🚀
on:
  push:
    paths:
      - 'data_warehouse/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt -h"
          dbt_project_folder: "data_warehouse"
