name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    paths:
      - 'data_warehouise/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: dbt-run
        id: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt -h"
          dbt_project_folder: "."
